repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

  - name: mittwald
    url: https://helm.mittwald.de

  - name: sealed-secrets
    url: https://bitnami-labs.github.io/sealed-secrets

  - name: altinity
    url: https://helm.altinity.com/

  - name: redpanda
    url: https://charts.redpanda.com

releases:
  - name: cert-manager
    chart: oci://quay.io/jetstack/charts/cert-manager
    namespace: cert-manager
    set:
      - name: crds.enabled
        value: true

  - name: postgresql
    chart: bitnami/postgresql
    namespace: postgresql
    values:
      - secretAnnotations:
          replicator.v1.mittwald.de/replication-allowed: "true"
          replicator.v1.mittwald.de/replication-allowed-namespaces: "platform"
      - auth:
          database: banking_platform

  - name: kubernetes-replicator
    chart: mittwald/kubernetes-replicator

  - name: sealed-secrets
    chart: sealed-secrets/sealed-secrets
    namespace: kube-system
    set:
      - name: fullnameOverride
        value: sealed-secrets-controller

  - name: clickhouse
    chart: altinity/clickhouse
    namespace: clickhouse
    disableValidationOnInstall: false
    set:
      - name: clickhouse.defaultUser.allowExternalAccess
        value: true

  - name: redpanda
    chart: redpanda/redpanda
    namespace: redpanda
    set:
      - name: statefulset.replicas
        value: 1
      - name: config.cluster.auto_create_topics_enabled
        value: true
      - name: tls.enabled
        value: false
      - name: external.service.enabled
        value: false
