repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

  - name: mittwald
    url: https://helm.mittwald.de

releases:
  - name: postgresql
    chart: bitnami/postgresql
    namespace: postgresql
    values:
      - secretAnnotations:
          replicator.v1.mittwald.de/replication-allowed: "true"
          replicator.v1.mittwald.de/replication-allowed-namespaces: "svcs"

  - name: kubernetes-replicator
    chart: mittwald/kubernetes-replicator