repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

  - name: mittwald
    url: https://helm.mittwald.de

  - name: sealed-secrets
    url: https://bitnami-labs.github.io/sealed-secrets

releases:
  - name: cert-manager
    chart: oci://quay.io/jetstack/charts/cert-manager
    namespace: cert-manager
    set:
      - name: crds.enabled
        value: true

  - name: postgresql
    chart: bitnami/postgresql
    namespace: postgresql
    values:
      - secretAnnotations:
          replicator.v1.mittwald.de/replication-allowed: "true"
          replicator.v1.mittwald.de/replication-allowed-namespaces: "platform"
      - auth:
          database: banking_platform

  - name: kubernetes-replicator
    chart: mittwald/kubernetes-replicator

  - name: sealed-secrets
    chart: sealed-secrets/sealed-secrets
    namespace: kube-system
    set:
      - name: fullnameOverride
        value: sealed-secrets-controller