apiVersion: v1
kind: Service
metadata:
  name: account-svc
spec:
  selector:
    app.kubernetes.io/name: account-svc
  ports:
    - name: server
      protocol: TCP
      port: 8080
      targetPort: 8080