apiVersion: v1
kind: Service
metadata:
  name: confirmation-of-payee-svc
spec:
  selector:
    app.kubernetes.io/name: confirmation-of-payee-svc
  ports:
    - name: server
      protocol: TCP
      port: 8080
      targetPort: 8080
