apiVersion: clickhouse.com/v1alpha1
kind: ClickHouseCluster
metadata:
  name: clickhouse-cluster
  namespace: clickhouse-cluster-system
spec:
  replicas: 1
  dataVolumeClaimSpec:
    resources:
      requests:
        storage: 1Gi
  settings:
    defaultUserPassword:
      passwordType: password
      secret:
        name: clickhouse-password-secret
        key: password