apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: clickhouse-password-secret
  namespace: clickhouse-cluster-system
  annotations:
    replicator.v1.mittwald.de/replicate-to: "platform"
spec:
  encryptedData:
    password: AgBQP386NnZcTF6S98yP3rXPwh9FXGUuxSaNB0h1KhZmr6YT/5xUdGu4kC4xBHidLbaQcj3yWSWa4F1IWYkvZ+JnB860l7TV9s6uuWK+knv0z2hgPOvIjZGcLHSYTodT1J1+s5XMSxbviHx/QGoBYEHXX+LNZ4IFV7uxAxQ5OjLlhISmJ9+ZGnb54Z22NVLf/DogQWLJFliLa4Au4K96tjl/mpUrs5Xb3jRtMXN89h3XDHBeESC3DyXrzla4xwrGwdS8cJRP48EYjxWCkWjMZKFV7pulFuO8UO7kg5CUIBZpsx1/FBPaz/tTr/A3BW/kEExEFGpNmqmh4Nm+n7np3q3Q67MuV4PdCys1byaqnG3XDcrDQWKulaT4ZPuwkZjsq6sHJWQHV2I4ZWyBfCjeayUneYYCiJ82snmSuAjniSBThhHpRSBPuXF3E+ic9lO9zO7xVMU0hY+QBdRYLKVcAcQ+SBjwsZJ0KbsgfoxukPtrdSQ6wAFYV4zQ709f/Bo5oWJ1JKPtOemW+iV6ngxLVSR6JsP+mVG8u0Em0f3WBCezH0L4H0mvJ9sk+xxI03esjmEV75zgjopJzz/nUcHL31dvFk1hFY6zx1RVClFfpLT6FbMs3Vrtnza8jFQYPjf4aLwvQ7bhWllIOghm1fNdp1m5WyUPcsHYSb5/meGqXmacjQMeJFl7BneMaYFytvrUJWXg4mOladF5ZNq2Y2wu+uL4hHCNCCvh5fyeRdJsrHv729k=
  template:
    metadata:
      name: clickhouse-password-secret
      namespace: clickhouse-cluster-system