apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jwt-secret
  namespace: platform
spec:
  encryptedData:
    jwt-secret: AgAmsVSjZon6syGLKxVVYlSEPNLA5fHliuK3akpH0XCU8yH1aNLIPhskx1K2uwvOEwim4jDx6XbI9LljRvbJyMMYrDGTlU/ofvmOAKWC7BI9YLFYYkOJJYHWwIFI2m62gQ6hyC6jwB0A81LIVOI8psjSJ4IZEd+iazmFaPz3e/7jVzi08Jm8/wh71Yh6lU5OYdzHOiPJijUawC+qkRHyh/8uuQ+Gttyk0SsPxxPV5Tgf+OHpUXtSK0z11rG6DAHUCcwLLl2NczW2haIjhHuV1O1ZTOSUR+ByFbjQ3kV2hQ5ZUlRw6WU7QRVt/mPYUrmOY5klaL/FOk5ImihXks2GLm+llUVkBpHHd1rZFBzAB4eTbytbSI5szTX6VikkdgNDAm8aBPrCbIa23xro39tewT2f5A8k4nRvRIOTCHdCqXj8TYv3QV1yhUl8NC5+/uxWSfxXYrUZQiBqEY7feZImSUKABA+C4sfh+pE0RbFt0JJpBISXpt32UNKUjWaRkxjv+hVzQapRtORbIlOf1WAQwsR1f6eKwVTfp38/g7RndFLHVSJOT/v95fuyhktCWsCqb9IjxJi9FM63PQdWhgCGHmx08P5gzNMtTwx3m2Nhe9fRDxS4To8oLsGVpCtJGicdk/lDSI6pyQT4cSgWAZ+J5IJgrMdPqVvUgF+UW7cnvmNJnhDjBAGeIRzQ65Lw9s7bHG03LDtyLD6uFyMKklULTk59WfZoc316ZqpOtiRKrM8k+oU=
  template:
    metadata:
      name: jwt-secret
      namespace: platform
