---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jwt-secret
  namespace: platform
spec:
  encryptedData:
    jwt-secret: AgAqxTJ+oAFl4oRKjubq2m6njRjsMeIuNaqn/wqDi0bHx06WVUXhjPrjYkCvXf4/Sv+aGNlXHM+X7iolfDUcwZS3DMUBRHhO8dAhgqAFn8hi8oLmlBdVmET6J5DYtkNlEDpuYGvnibtX06Yc2/3WKjVjZMnBLo3VuEm4rbzdSQjNm9NDTGUqbeyHsucTAtX/Hut2hDmBsgyp++QDsaRw9gKZRSmeSYZwRHThhntWuvwf+cvQ9xULgVUV5TU1nU/WQCZL/bTA5On/T1ixrKimbGM95UvM2KHkmtRJoVEu3ayayJew4+d44QiP6zv3Ngtbrxdy5sgL84sGLC5URGFKsV6BRJtuJvZ4ZbMY2Z2X02AqEzm4NGBoVREfaAa5bkkFtM/DjZed8isNPaViPnEoo9tvZ+mXcvKRrhkPcH5bi3LoxtLG2EcrrnYNwtNmgScyuYV3HYAlHNNi3/UvrfymnX8lDOTJi3c6eZj8PV+NP1bwzaFQig1wRjop7ujAPiW0iWunlKEQgq8b/3/ukOQFDskTzJwLoOIhqclDAXcAHmJZ7dr5iMhj0FFXt0fcjmXFflokZfImN1F4Zjf1IiudynAdrTLZGhDSJ+XeLjCv9+3NH4hrZHlj6brz+1PIKR+WmIL4IAE86c96/zdPwnAz4m4obeIZcwEOtPWtUqvolDyHcBpylLbdFYozCxI1smBSG8JZTWO3Xa9dCDS8qzN5vuhIjEbOhir+K79LK2rh/9oihcLiw8X615FbrREhx+gXhjmD+rsC7wC5sGpMnmxD2EWb
  template:
    metadata:
      name: jwt-secret
      namespace: platform
