apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: svcs
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
    - git:
        repoURL: https://github.com/ewancrowle/banking-platform-gitops.git
        revision: HEAD
        directories:
          - path: svcs/*
  template:
    metadata:
      name: "{{.path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/ewancrowle/banking-platform-gitops.git
        targetRevision: HEAD
        path: "{{.path.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "platform"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true